\# module - CV
.heading "Education"
.TS
tab(|) nospaces;
lw24|lx.
T{
.B "Eastman School of Music"
T}|T{
.B "Doctor of Philosophy" ,
Music Composition (in progress)
.br
.B "Master of Arts" ,
Music Composition (05/2023)
.br
.B "Catherine Filene Shouse Arts Leadership Certificate"
(05/2023)
.sp 0.2
T}
T{
.B "Pennsylvania State University"
T}|T{
.B "Bachelor of Music" ,
Music Composition (05/2021)
.sp 0.2
T}
.TE
